### ISSUE TITLE
Tests Enhancements

### ISSUE THREAD

**Issue by folkvir** [RAN3D/foglet-core#17]
Cause of the growing number of tests. **Tests become very huge and heavy to run on browsers due to the number of WebRTC connections on the same page.** 

**Karma** is working on a parallel solution to run parallel tests but meanwhile we reach test problems with the growing number of webRTC connections.

My idea to minimize the number of foglets loaded during tests and minimize the number of webrtc connection is **_to load a fixed number of foglets before tests and ONLY use them_** for testing purposes.

Think this would be a good idea to work like this. 

Another solution is to split tests and apply each karma-test on each file in order to have a single page by test file and minimize the number of webrtc connection by pages. 
This leads to problems: 
* global coverage become unavailable.
* tests duration is longer than the previous solution

Need to quickly find a solution.

If someone has a better idea, comment here.

**Comment by folkvir** [comment]
Found this: https://github.com/rschuft/karma-sharding

Testing by implementing this into foglet-scripts.

For the moment this is working as expected.

**Comment by folkvir** [comment]
Latest commit of the branch firefox-latest is ok:
Windows: https://ci.appveyor.com/project/folkvir/foglet-core/build/1.0.31
Linux: https://travis-ci.org/RAN3D/foglet-core/builds/287965959?utm_source=github_status&utm_medium=notification

The conclusion is: 
* Always close each foglet before done() is called in each test
* Do not put a lot of foglets in each tests files
* Use the sharding proposition in order to load each test file in a different browsers

Enhancement of the foglet-scripts sharding: need a config options such as:
`"sharding": true|false`
If true we put the first browser in the object browsers to fit the number of test files.
Seems to be a good idea.

* Make a PR on foglet-scripts
* Release foglet-scripts to 0.2.4
* Update foglet-core#firefox-latest
* Make a PR on foglet-core with firefox-latest branch

**Comment by rschuft** [comment]
One of the enhancements I'm intending to make to karma-sharding is scaling the browsers array automatically based on either a number (capped at the number of specs) or the string 'auto' to just match the spec count.  I had thought about using the following config for example:

```javascript
{
  sharding: {
    // defaults to false which will not touch the browsers array unless it exceeds the spec count
    scaleBrowsers: 'auto' // 'auto' matches the count of specs, a # will be that number of sets
  }
}
```

**Comment by Callidon** [comment]
To comment on "Always close each foglet before done() is called in each test":

I think this is not relevant at all: you simply assign undefined to each foglet, but this is not ensure you that WebRTC connections are garbaged too. Additionally, this is a very unnecessary operation, as it would happens naturally after `done` is called, as each foglet variable only exist within a specific `it` callback.

We always knew that running each test suite in a separate browser window is a good suitable solution.
So deleting foglets or limiting the number of foglets per test is, in my opinion, are tiresome optimizations with low benefits.

Next, I am note convinced about using karma-sharding. It is handy for sure, but how exactly are we suppose to handle the case where **a user want to execute each test against various type of browsers** (Firefox, Chrome, etc) ? The PR proposed in foglet-scripts https://github.com/RAN3D/foglet-scripts/pull/4 make impossible such use case. Even if we address this, running each test suite against each type of browser in distinct browser instances will be very costly.

**Comment by folkvir** [comment]
@rschuft Thank you, this is exactly what i intended to do with my PR. 

@Callidon About closing foglets, i thought that engaging the garbage processing before calling done() was a good idea to help to close WebRTC connection. I agree it is completely redundant. But for the moment I did not find another solution to clearly close connections. This is just the beginning of a solution.
 
Cause of https://github.com/ran3d/neighborhood-wrtc behavior we do not have the right way to clearly close a bucket of connections. An "arc" is place to the dying set and is destroyed when the timeout reached its term. We also have a disconnect method that will call destroy method of simple-peer package. But the disconnect behavior is not clearly proofed. For the moment the best way is to close the page to definitively close all webrtc connections. 
**I will search in this direction to see if calling the "disconnect" method will solve our problems.**

Meanwhile I propose karma-sharding to solve our problems. If you want to execute each test against a various type of browsers just put `{ "sharding": false }`. It will just use the normal behavior or Karma. But i agree, currently with this PR this is impossible to use both sharding option and different kind of browsers.

**Comment by folkvir** [comment]
@Callidon 
https://github.com/RAN3D/foglet-core/tree/firefox-latest
* A lot of problems solved
* Packages updated to their last version
* remove example
Tests are running perfectly. I tested by doing 10 times the same `npm test` command and no error found. 
The problem is now on TravisCI. As it can be very long to build or tests (cause of the number of simultaneous tests on the platform) this leads to sometimes crash firefox. 

Other enhancement ideas ?

**Comment by Callidon** [comment]
Considering that all tests now run on Node.js (using @folkvir mock) and that foglet-scripts is pending deprecation, maybe we can close this now?

**Comment by folkvir** [comment]
Yes, tests have to be run without the WebRTC communication layer to avoid network error. We can close this.
