### ISSUE TITLE
Distinct streams are causaly dependent  

### ISSUE THREAD

**Issue by nhaouari** [RAN3D/foglet-core#24]
Using streamBroadcast() function in Communication, if we sent two distinct streams successively, they are causally dependent by default, since, by default, FIFO broadcast is used in the class Broadcast.

**Comment by folkvir** [comment]
Error was: listenerCount not found?
This function is part of readable-stream (https://github.com/nodejs/readable-stream). The version used is 2.3.6 is almost (not all) versions of readable-stream. This error is never encountered with my version.  Perhaps your node_modules are not update to date. 
I close this issue. If you have any problems in the future, reopen this issue.
