### ISSUE TITLE
Running foglet-core on nodejs

### ISSUE THREAD

**Issue by fsvieira** [RAN3D/foglet-core#26]
Hi,

Not sure if this project is inactive, because its not updated for almost years, if this is the case its sad because its really cool project.

Anyway I run the project on the browser and its great, but I really would like to have nodes running on node, I know that project uses webrtc but now that is a the https://github.com/node-webrtc/node-webrtc (I have tested with simple-peer) and it works fine.

I am not sure if it would be possible to use it with this project, I tried to look at the code but I didn't figure out how I could do it. 

Thanks.

**Comment by fsvieira** [comment]
Never mind, I just figure it out:

```javascript
const {Foglet} = require('./foglet-core');
const wrtc = require('wrtc');
  
// let's create a simple application that send message in broadcast
const fog = new Foglet({
  // id: 'myfogletid', // default we use uuid/v4 generated id
  rps: {
    type: 'spray-wrtc', // we choose Spray as a our RPS,
    options: {
      protocol: 'my-awesome-broadcast-application', // the name of the protocol run by our app
      webrtc: { // some WebRTC options
        wrtc,
        trickle: true, // enable trickle
        iceServers : [] // define iceServers here if you want to run this code outside localhost
      },
      signaling: { // configure the signaling server
        // address: 'http://signaling.herokuapp.com', // put the URL of the signaling server here
        address: 'http://localhost:3000',
        room: 'my-awesome-broadcast-application' // the name of the room for the peers of our application
      }
    }
  }
});
```

**Comment by folkvir** [comment]
Oh thank you! yes this project is not anymore maintained due to lack of times.
If you encounter any problems do not hesitate to ask by opening issues, i'll answer as soon as possible.
Btw, you can pass any wrtc interface compliant objects in the options object like you did to use any custom wrtc version.

**Comment by fsvieira** [comment]
Ok, thank you. Until now I am very happy with foglet, also I am impressed that something that is not updated for 3 years still works so well. Right now I am trying to implement a distributed queue on foglet, I had encounter some minor issues so when I finish I will probably open some issues. Thanks
